name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Node.js (no cache to silence lockfile warning)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Show tool versions
        run: |
          node -v
          npm -v
          java -version

      # Create a lockfile if missing, then install deterministically
      - name: Install dependencies (lockfile-safe)
        run: |
          set -e
          npm config set fund false
          npm config set audit false
          if [ -f package-lock.json ]; then
            echo "Lockfile present -> npm ci"
            npm ci || npm ci --legacy-peer-deps
          else
            echo "No lockfile -> generating one"
            npm install --package-lock-only
            npm ci || npm install --legacy-peer-deps
          fi

      - name: Ensure Capacitor toolchain
        run: |
          npm i -D @capacitor/cli@5.7.8
          npm i @capacitor/android@5.7.8

      - name: Build web assets
        run: npm run build

      - name: Recreate and sync Android platform
        run: |
          rm -rf android
          npx cap add android
          npx cap sync android

      - name: Ensure AndroidX flags
        run: |
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties

      - name: Make Gradle wrapper executable
        run: chmod +x android/gradlew

      - name: Build APK (debug)
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error