name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install

      - name: Install Capacitor Android Platform
        run: npm install @capacitor/android@5

      - name: Build React app
        run: npm run build

      - name: Add Android platform
        run: npx cap add android || echo "android folder already exists"

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build APK with Gradle
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
